export const CONTACTS = [
  {
    id: "c1",
    name: "Сергей Р.",
    initial: "С",
    acct: "8921 362 190",
    tone: "lime",
    img: "/ava1.png",
  },

  {
    id: "c2",
    name: "Ферина К.",
    initial: "Ф",
    acct: "7740 112 233",
    tone: "lime",
    img: "/ava2.png",
  },
  {
    id: "c3",
    name: "Дарья Т.",
    initial: "Д",
    acct: "6650 998 877",
    tone: "dark",
    img: "/ava3.png",
  },
  {
    id: "c4",
    name: "Баюр С.",
    initial: "Б",
    acct: "5512 334 455",
    tone: "blue",
    img: "/ava4.png",
  },
  {
    id: "c5",
    name: "Кристина",
    initial: "К",
    acct: "4423 889 900",
    tone: "lime",
    img: "/ava5.png",
  },
  {
    id: "c6",
    name: "Алина В.",
    initial: "А",
    acct: "3314 556 677",
    tone: "violet",
    img: "/ava6.png",
  },

  {
    id: "c7",
    name: "Олег П.",
    initial: "О",
    acct: "2298 111 002",
    tone: "lime",
    empty: true,
  },
  {
    id: "c8",
    name: "Марина С.",
    initial: "М",
    acct: "1187 223 114",
    tone: "lime",
    empty: true,
  },
  {
    id: "c9",
    name: "Виктор Л.",
    initial: "В",
    acct: "9076 334 225",
    tone: "lime",
    empty: true,
  },
  {
    id: "c10",
    name: "Нина К.",
    initial: "Н",
    acct: "8065 445 336",
    tone: "lime",
    empty: true,
  },
  {
    id: "c11",
    name: "Павел Д.",
    initial: "П",
    acct: "7054 556 447",
    tone: "lime",
    empty: true,
  },
  {
    id: "c12",
    name: "Юлия М.",
    initial: "Ю",
    acct: "6043 667 558",
    tone: "lime",
    empty: true,
  },
  {
    id: "c13",
    name: "Роман Г.",
    initial: "Р",
    acct: "5032 778 669",
    tone: "lime",
    empty: true,
  },
  {
    id: "c14",
    name: "Света А.",
    initial: "С",
    acct: "4021 889 770",
    tone: "lime",
    empty: true,
  },
  {
    id: "c15",
    name: "Тимур Б.",
    initial: "Т",
    acct: "3010 990 881",
    tone: "lime",
    empty: true,
  },
  {
    id: "c16",
    name: "Лена В.",
    initial: "Л",
    acct: "2009 101 992",
    tone: "lime",
    empty: true,
  },
];

export const CARDS = [
  {
    id: "k1",
    holder: "Егор Масло",
    num: "2451",
    balance: 521098.31,
    cur: "₽",
    code: "RUB",
    tone: "lime",
    full: "5536 9140 7782 2459",
    exp: "09/28",
    cvc: "418",
    acct: "40817 810 2 0000 5210 983",
  },
  {
    id: "k2",
    holder: "Егор Масло",
    num: "0095",
    balance: 4250.0,
    cur: "$",
    code: "USD",
    tone: "dark",
    full: "4276 3801 5562 0095",
    exp: "13/27",
    cvc: "204",
    acct: "40817 840 5 0000 1124 110",
  },
  {
    id: "k3",
    holder: "Егор Масло",
    num: "1122",
    balance: 1180.5,
    cur: "€",
    code: "EUR",
    tone: "light",
    full: "2200 7004 3391 1122",
    exp: "03/29",
    cvc: "736",
    acct: "40817 978 8 0000 1200 001",
  },
];

export const LIMITS = [
  {
    id: "transfer",
    key: "lim.transfer",
    sub: "lim.day",
    min: 0,
    max: 1000000,
    step: 5000,
    def: 150000,
  },
  {
    id: "withdraw",
    key: "lim.withdraw",
    sub: "lim.day",
    min: 0,
    max: 500000,
    step: 5000,
    def: 100000,
  },
  {
    id: "online",
    key: "lim.online",
    sub: "lim.day",
    min: 0,
    max: 1000000,
    step: 5000,
    def: 200000,
  },
  {
    id: "single",
    key: "lim.single",
    sub: "lim.max",
    min: 1000,
    max: 1000000,
    step: 1000,
    def: 300000,
  },
];

export const INIT_TX = [
  {
    id: "t1",
    name: "m.grocery",
    cat: "c.groceries",
    group: "g.yesterday",
    amount: -521,
    icon: "expense",
    card: "•• 2451",
  },

  {
    id: "t2",
    name: "m.orderRefund",
    cat: "c.market",
    group: "g.yesterday",
    amount: 1997,
    icon: "expense",
    card: "acc",
  },

  {
    id: "t0",
    name: "m.longsub",
    cat: "c.subscriptions",
    group: "g.yesterday",
    amount: -399,
    icon: "expense",
    card: "•• 2451",
  },
  {
    id: "t3",
    name: "m.taxi",
    cat: "c.transport",
    group: "g.yesterday",
    amount: -592,
    icon: "expense",
    card: "•• 2451",
  },
  {
    id: "t4",
    name: "m.steam",
    cat: "c.games",
    group: "g.yesterday",
    amount: -19.99,
    cur: "$",
    icon: "expense",
    card: "•• 0095",
  },
  {
    id: "t5",
    name: "m.mobileTopup",
    cat: "c.mobile",
    group: "g.yesterday",
    amount: -500,
    icon: "expense",
    card: "•• 2451",
  },
  {
    id: "t6",
    name: "m.cafePolka",
    cat: "c.cafe",
    group: "g.jun21",
    amount: -754,
    icon: "expense",
    card: "•• 2451",
  },
  {
    id: "t7",
    name: "m.exchange",
    cat: "c.exchange",
    group: "g.jun21",
    amount: -15000,
    icon: "send",
    card: "•• 2451",
  },
  {
    id: "t8",
    name: "m.course",
    cat: "c.education",
    group: "g.jun21",
    amount: -49,
    cur: "$",
    icon: "expense",
    card: "•• 0095",
  },
  {
    id: "t9",
    name: "m.grocery",
    cat: "c.groceries",
    group: "g.jun20",
    amount: -494,
    icon: "expense",
    card: "•• 2451",
  },
  {
    id: "t10",
    name: "m.food",
    cat: "c.fastfood",
    group: "g.jun20",
    amount: -516.4,
    icon: "expense",
    card: "•• 2451",
  },

  {
    id: "t10b",
    name: "m.food",
    cat: "c.fastfood",
    group: "g.jun20",
    amount: -516.4,
    icon: "expense",
    card: "•• 2451",
  },
  {
    id: "t11",
    name: "m.transferIgor",
    cat: "c.transfers",
    group: "g.jun20",
    amount: 2000,
    icon: "income",
    card: "acc",
  },
  {
    id: "t12",
    name: "m.hotelRefund",
    cat: "c.travel",
    group: "g.jun20",
    amount: 180,
    cur: "€",
    icon: "income",
    card: "•• 1122",
  },
  {
    id: "t13",
    name: "m.salary",
    cat: "c.income",
    group: "g.jun18",
    amount: 84000,
    icon: "income",
    card: "acc",
  },
  {
    id: "t14",
    name: "m.pharmacy",
    cat: "c.health",
    group: "g.jun18",
    amount: -642.3,
    icon: "expense",
    card: "•• 2451",
  },
  {
    id: "t15",
    name: "m.utilities",
    cat: "c.utilities",
    group: "g.jun18",
    amount: -4830.12,
    icon: "expense",
    card: "•• 2451",
  },
  {
    id: "t16",
    name: "m.musicSub",
    cat: "c.subscriptions",
    group: "g.jun18",
    amount: -5.99,
    cur: "$",
    icon: "expense",
    card: "•• 0095",
  },

  {
    id: "t16b",
    name: "m.fine",
    cat: "c.services",
    group: "g.jun18",
    amount: 800,
    icon: "income",
    card: "acc",
  },
  {
    id: "t17",
    name: "m.cafePolka",
    cat: "c.cafe",
    group: "g.jun15",
    amount: -318,
    icon: "expense",
    card: "•• 2451",
  },
  {
    id: "t18",
    name: "m.scooter",
    cat: "c.transport",
    group: "g.jun15",
    amount: -149,
    icon: "expense",
    card: "•• 2451",
  },
  {
    id: "t19",
    name: "m.transferFerina",
    cat: "c.transfers",
    group: "g.jun15",
    amount: 3500,
    icon: "income",
    card: "acc",
  },
  {
    id: "t20",
    name: "m.bookstore",
    cat: "c.hobby",
    group: "g.jun15",
    amount: -24.9,
    cur: "€",
    icon: "expense",
    card: "•• 1122",
  },
  {
    id: "t21",
    name: "m.gas",
    cat: "c.auto",
    group: "g.jun12",
    amount: -2700,
    icon: "expense",
    card: "•• 2451",
  },
  {
    id: "t22",
    name: "m.gym",
    cat: "c.health",
    group: "g.jun12",
    amount: -39,
    cur: "$",
    icon: "expense",
    card: "•• 0095",
  },
  {
    id: "t23",
    name: "m.market",
    cat: "c.market",
    group: "g.jun12",
    amount: -2190,
    icon: "expense",
    card: "•• 2451",
  },
  {
    id: "t24",
    name: "m.cashback",
    cat: "c.bonus",
    group: "g.jun12",
    amount: 1247.5,
    icon: "income",
    card: "acc",
  },
  {
    id: "t25",
    name: "m.theater",
    cat: "c.fun",
    group: "g.jun10",
    amount: -2400,
    icon: "expense",
    card: "•• 2451",
  },
  {
    id: "t26",
    name: "m.taxi",
    cat: "c.transport",
    group: "g.jun10",
    amount: -410,
    icon: "expense",
    card: "•• 2451",
  },
  {
    id: "t27",
    name: "m.insurance",
    cat: "c.insurance",
    group: "g.jun10",
    amount: -5400,
    icon: "expense",
    card: "•• 2451",
  },
  {
    id: "t28",
    name: "m.cinema",
    cat: "c.fun",
    group: "g.jun10",
    amount: -12.5,
    cur: "€",
    icon: "expense",
    card: "•• 1122",
  },
  {
    id: "t29",
    name: "m.electronics",
    cat: "c.electronics",
    group: "g.jun8",
    amount: -129,
    cur: "$",
    icon: "expense",
    card: "•• 0095",
  },
  {
    id: "t30",
    name: "m.atm",
    cat: "c.cash",
    group: "g.jun8",
    amount: -10000,
    icon: "expense",
    card: "•• 2451",
  },
  {
    id: "t31",
    name: "m.donation",
    cat: "c.charity",
    group: "g.jun8",
    amount: -1000,
    icon: "send",
    card: "•• 2451",
  },
  {
    id: "t32",
    name: "m.ticketRefund",
    cat: "c.travel",
    group: "g.jun8",
    amount: 1450,
    icon: "income",
    card: "acc",
  },
  {
    id: "t33",
    name: "m.barber",
    cat: "c.beauty",
    group: "g.jun5",
    amount: -1800,
    icon: "expense",
    card: "•• 2451",
  },
  {
    id: "t34",
    name: "m.delivery",
    cat: "c.fastfood",
    group: "g.jun5",
    amount: -780.4,
    icon: "expense",
    card: "•• 2451",
  },
  {
    id: "t35",
    name: "m.transferDarya",
    cat: "c.transfers",
    group: "g.jun5",
    amount: 5000,
    icon: "income",
    card: "acc",
  },
  {
    id: "t36",
    name: "m.parking",
    cat: "c.auto",
    group: "g.jun5",
    amount: -8,
    cur: "€",
    icon: "expense",
    card: "•• 1122",
  },
  {
    id: "t37",
    name: "m.internet",
    cat: "c.services",
    group: "g.jun3",
    amount: -650,
    icon: "expense",
    card: "•• 2451",
  },
  {
    id: "t38",
    name: "m.vetclinic",
    cat: "c.pets",
    group: "g.jun3",
    amount: -3250,
    icon: "expense",
    card: "•• 2451",
  },
  {
    id: "t39",
    name: "m.grocery",
    cat: "c.groceries",
    group: "g.jun3",
    amount: -612.8,
    icon: "expense",
    card: "•• 2451",
  },
  {
    id: "t40",
    name: "m.interest",
    cat: "c.income",
    group: "g.jun1",
    amount: 1872.4,
    icon: "income",
    card: "acc",
  },
  {
    id: "t41",
    name: "m.flowers",
    cat: "c.gifts",
    group: "g.jun1",
    amount: -2300,
    icon: "expense",
    card: "•• 2451",
  },
  {
    id: "t42",
    name: "m.kinoSub",
    cat: "c.subscriptions",
    group: "g.jun1",
    amount: -4.99,
    cur: "$",
    icon: "expense",
    card: "•• 0095",
  },
  {
    id: "t43",
    name: "m.tax",
    cat: "c.taxes",
    group: "g.may29",
    amount: -7600,
    icon: "expense",
    card: "•• 2451",
  },
  {
    id: "t44",
    name: "m.hotelRefund",
    cat: "c.travel",
    group: "g.may29",
    amount: 7400,
    icon: "income",
    card: "acc",
  },
  {
    id: "t45",
    name: "m.pharmacy",
    cat: "c.health",
    group: "g.may29",
    amount: -418.6,
    icon: "expense",
    card: "•• 2451",
  },
  {
    id: "t46",
    name: "m.cafePolka",
    cat: "c.cafe",
    group: "g.may27",
    amount: -265,
    icon: "expense",
    card: "•• 2451",
  },
  {
    id: "t47",
    name: "m.delivery",
    cat: "c.fastfood",
    group: "g.may27",
    amount: -14.5,
    cur: "€",
    icon: "expense",
    card: "•• 1122",
  },

  {
    id: "t48",
    name: "m.kinoSub",
    cat: "c.subscriptions",
    group: "g.feb30",
    amount: -299,
    icon: "expense",
    card: "•• 0095",
  },
  {
    id: "t49",
    name: "m.grocery",
    cat: "c.groceries",
    group: "g.feb30",
    amount: -450,
    icon: "expense",
    card: "•• 2451",
  },
];
